import React from 'react';
import { Link } from "react-router-dom";
function Agile() {
  return (
    <div className="container_components">
      <h1>Agile</h1>
      <h3 className="subtitle">Introduction</h3>
      <p>La méthodologie agile est une méthode de développement de logiciel largement utilisée et reconnue dans le monde du travail à travers le monde. Cette approche vise à améliorer la qualité et la rapidité de développement d’un projet tout en réduisant le coût d’un projet via une meilleure organisation du projet. Elle repose sur une approche d’itération et de cycles de développement courts, ce qui permet un meilleur suivi de la qualité d’un projet ainsi qu’une livraison du projet efficace et rapide.</p>
      <p>L’agilité est actuellement la méthodologie de développement de logiciel la plus utilisée dans le monde au sein des entreprises ces dernières années. En effet, cette approche se caractérise par sa grande flexibilité, permettant aux développeurs de mieux s’adapter aux changements durant un projet. Les cycles courts de développement, de test et de livraison favorisent une réactivité accrue. Cela permet à une équipe de développement de répondre plus facilement aux demandes du client durant un projet tout en livrant rapidement un logiciel fonctionnel. La communication que met en avant l’agilité favorise les échanges entre les membres de l’équipe, ce qui permet aux développeurs de partager plus facilement leurs idées entre eux ainsi que de pouvoir ensemble résoudre des problèmes en trouvant des solutions qui feront avancer correctement le logiciel.</p>
      <p>D'après une étude sur l'état de la méthodologie Agile en 2022, il est indiqué que l'Agile est de plus en plus largement adoptée en entreprise, sous différentes formes. L'Agile Scrum est la méthode la plus répandue au sein des équipes avec une utilisation de 87 % contre 54 % il y a seulement deux ans. Cette croissance significative de l'utilisation de l'Agile Scrum s'explique principalement par l'efficacité des pratiques agiles qui permettent notamment d'accélérer le délai de mise sur le marché.</p>
      <p>Actuellement, la gestion de projet est un facteur clé dans la réussite d’une entreprise en matière de rapidité de développement d’un logiciel ainsi que de la qualité de celui-ci. Grâce à cette méthodologie, les entreprises ont un meilleur taux de réussite de projet avec une clientèle plus satisfaite.</p>
      <br></br>
      <h3 className="subtitle">Mon expérience vécue</h3>
      <p>Depuis début juillet 2024 jusqu’à aujourd’hui, j’ai la chance de pouvoir travailler sur de nombreux projets Airbus, y compris le projet WebFTI. Ce projet a pour but de développer des widgets qui pourront être utilisés par d’autres développeurs Airbus via React sous forme de bibliothèque, ce qui les aidera dans leur développement futur pour des applications web qui serviront à Airbus.</p>
      <p>La méthodologie agile Scrum avait été mise en place au début de la création de l’équipe, car notre équipe travaille sur de nombreux projets Airbus en même temps. Il était nécessaire d’avoir une méthodologie qui nous permettrait d’avoir un excellent suivi avec notre client pour que l’équipe et le client puissent avoir un suivi régulier sur l’avancée des différents projets ainsi que de pouvoir faire des modifications à la fin d’un cycle pour être sûr d’avoir un produit qui réponde aux attentes du client.</p>
      <p>Durant le projet, l’équipe n’a pas eu beaucoup de difficulté à mettre en place la méthodologie agile Scrum, car de nombreux membres de l’équipe avaient de l’expérience dans la mise en place de cette méthodologie dans un projet. De plus, nous avons un Scrum Master qui est là pour que la méthodologie soit bien comprise de tous et bien appliquée au sein des différents projets qui nous sont demandés. Grâce à cela, nous avons réussi à satisfaire chaque demande du client en apportant des modifications à chaque fin de cycle court pour que le produit final soit une réussite. L’Agile Scrum a bien été mise en place durant l’ensemble du développement de la bibliothèque de widgets, ce qui a permis de rendre un travail fonctionnel et en corrélation avec les exigences de notre client.</p>
      <br></br>
      <h3 className="subtitle">Mon niveau de compétence</h3>
      <p>Actuellement, avec les différents projets que j’ai réalisés, je considère que j’ai une bonne maîtrise de l’Agile Scrum. En effet, je serais capable de m’insérer dans un nouveau projet avec cette méthodologie sans grande difficulté tout en respectant l’ensemble des points clés qui la concernent au sein d’une équipe.</p>
      <p>Je considère que je ne serais pas encore en capacité de gérer moi-même un projet qui suit la méthodologie Scrum comme un Scrum Master le ferait. J’ai donc encore une bonne marge d’apprentissage afin de me considérer comme un expert de ce domaine, même si j’ai les bases pour intégrer une équipe tout en respectant ces principes. Il faut aussi considérer que selon les domaines, l’entreprise et les projets, l’agilité peut être différente, ce qui en fait une compétence vaste nécessitant de l’expérience pour mieux la maîtriser.</p>
      <p>Selon moi, la méthodologie Agile Scrum est l’une des méthodologies les plus utilisées par les grandes entreprises du monde entier à travers de nombreux pays. De plus, de nombreux projets informatiques l’utilisent pour son efficacité et sa flexibilité. Son approche itérative permet de s’adapter rapidement aux changements fréquents, ce qui permet d’obtenir des résultats concrets plus rapidement. Sa popularité en fait une compétence clé à maîtriser pour que chaque projet informatique puisse être un succès.</p>
      <p>Grâce à ma formation, j’ai acquis cette compétence via, dans un premier temps, la théorie, puis via une formation pratique grâce à des projets concrets que j’ai eu la chance d’avoir durant mon cursus d’expert en ingénierie du logiciel. L’Agile Scrum peut paraître complexe au début, notamment en raison de ses principes et de sa structure. Cependant, avec des projets pratiques, cela devient rapidement notre quotidien et naturel. De plus, grâce à mon Scrum Master dans mon projet actuel, j’ai pu avoir une réunion explicative où j’ai pu poser toutes mes questions pour mieux comprendre les zones d’ombre que j’avais, et cela m’a beaucoup aidé à mes débuts dans ce projet, car les autres membres de l’équipe avaient déjà beaucoup d’expérience auparavant dans l’Agile Scrum.</p>
      <p>Durant mon quotidien de développeur et dans ma vie personnelle, j’essaie dans la majeure partie du temps d’utiliser l’Agile Scrum, car cette manière de s’organiser permet une meilleure gestion des délais ainsi qu’une gestion accrue de l’avancement de nos différents projets, qu’ils soient personnels ou professionnels. L’adaptabilité et la flexibilité que l’agilité procure permettent de pouvoir résoudre des imprévus tout en gardant une discipline dans nos projets. Actuellement, je souhaite gagner plus d’expérience en Agile Scrum pour me permettre dans le futur de pouvoir gérer une équipe dans un projet qui sera en Agile Scrum.</p>
      <p>Pour le moment, ma carrière n’a pas nécessité d’avoir un niveau très approfondi en Agile Scrum. Néanmoins, dans un futur proche, lorsque je souhaiterai me pencher davantage sur une carrière dans la gestion d’équipe, je me pencherai sur le sujet de manière plus approfondie en lisant le livre "Gestion de projet agile". Ce livre sera l’un des processus d’autoformation les plus importants dans ma carrière, car cela sera le passage d’un métier technique à un métier qui se concentrera davantage sur la gestion d’une équipe via la méthodologie Agile Scrum. Grâce à ce livre, j’apprendrai les détails qui me manquent actuellement pour me considérer comme un expert de cette compétence.</p>

    </div>
);
}

export default Agile